### ISSUE TITLE
About current tokens in get_random_walk func

### ISSUE THREAD

**Issue by wxx07** [atomistic-machine-learning/G-SchNet#1]
https://github.com/atomistic-machine-learning/G-SchNet/blob/74cea9b00bf27e62f7c324e4e6f3a7b6f1f45e23/utility_functions.py#L425

It seems to me that `current` here should be appended by indices of atoms, instead of sampled index from `avail`, right?
Is that a mistake or a misunderstanding of mine?

**Comment by NiklasGebauer** [comment]
Hey,
the line should be correct. The naming and comments might be a little confusing.
The positions and types of atoms are sorted at the end of the function according to the order in which they appear in the generation trace:

https://github.com/atomistic-machine-learning/G-SchNet/blob/74cea9b00bf27e62f7c324e4e6f3a7b6f1f45e23/utility_functions.py#L449-L452

The indices in `current` correspond to the atoms after they have been sorted according to `order` and not to the original atom indices in the input.
Hope this helps!

**Comment by wxx07** [comment]
I get it now. Thanks!
