### ISSUE TITLE
A bug in get_default_neighbors func

### ISSUE THREAD

**Issue by wxx07** [atomistic-machine-learning/G-SchNet#4]
Hi, I found a bug in `get_default_neighbors` func:
https://github.com/atomistic-machine-learning/G-SchNet/blob/74cea9b00bf27e62f7c324e4e6f3a7b6f1f45e23/utility_functions.py#L853-L865

It should be `return [list(range(0, i)) + list(range(i + 1, n_atoms)) for i in range(0, n_atoms)]` to return expected neighborhood indices matrix

**Comment by NiklasGebauer** [comment]
Yes, you are right, the implementation does not fit the doc-string, thanks!

I only use the function once here:
https://github.com/atomistic-machine-learning/G-SchNet/blob/74cea9b00bf27e62f7c324e4e6f3a7b6f1f45e23/utility_functions.py#L964
We only need the neighborhood list for `max_length-1` atoms, but of course this should be handled when calling the function and not inside the function. So I will change these two lines such that `get_default_neighbors` works as you (and my doc-strings) suggested.

**Comment by NiklasGebauer** [comment]
Fixed in https://github.com/atomistic-machine-learning/G-SchNet/commit/b6a38d37ce555c46c6959e1c72209908f26999c0.

Thanks again!
