### ISSUE TITLE
Concern about bias in each batch

### ISSUE THREAD

**Issue by wxx07** [atomistic-machine-learning/G-SchNet#5]
Hi, I wonder if you worried about bias in each batch, since the batch size is pretty small. In the extreme (and unlikely) case of batch size being 1, all samples in a batch belong to the same molecule.
Have you tried to construct each batch from sampling snapshots of traces gathering from a lot more molecules and compared the difference in behaviours of model?

**Comment by NiklasGebauer** [comment]
Hey, we are aware that the batches are biased, i.e. the number of steps (samples) in the batch is way higher than the number of molecules (in fact it is 2 * n_atoms * n_molecules). We have not tested the influence of this on the behavior of the model.

But there is an argument in the gschnet_script that lets you limit the number of steps drawn per molecule (--draw_random_samples, however, these are not sub-traces but uniformly randomly drawn steps from the complete trace). You could train a model where you increase the batch size and use this argument to limit the number of samples per molecule to e.g. 5 (or even 1 in the most extreme case). If you run such experiments, please feel free to post your findings!

https://github.com/atomistic-machine-learning/G-SchNet/blob/b6a38d37ce555c46c6959e1c72209908f26999c0/gschnet_script.py#L52-L56

**Comment by wxx07** [comment]
That is a convenient argument for testing. I may give it a try and let you know if I find something interesting :)
