### ISSUE TITLE
Upgrading to SchNetPack v2.0?

### ISSUE THREAD

**Issue by ameya98** [atomistic-machine-learning/G-SchNet#9]
SchNetPack v2.0 has a lot of new features. Do you think an upgrade is possible? Would it take very long to do?

**Comment by NiklasGebauer** [comment]
Hi Ameya,
yes it is possible. In fact, I already implemented (c)G-SchNet in SchNetPack 2.0 (and it took a lot of time).
I will link it in the README soon.
You can find the package here:
https://github.com/atomistic-machine-learning/schnetpack-gschnet/

However, it required me to rewrite the complete code base, so you will not be able to transfer any models. If you just want to reproduce our results from the NeurIPS paper on G-SchNet with QM9, I recommend to stick to this repository as it includes everything that we used. However, if you want to apply the model to other data sets or build on top of it you should definitely check out the new repo and start from there. It also includes example setups for QM9 but the analysis of generated molecules from this repository is missing (as the new repo targets experiments on new data sets and writing a general filtering script for all kinds of generated molecules is impossible).

Best,
Niklas
